// <auto-generated />
using System;
using Loyalty.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Loyalty.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20190714140617_lp_unique_added")]
    partial class lp_unique_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyGroupRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<bool>("IsArchived");

                    b.Property<long>("LoyaltyProductGroupId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Rule");

                    b.Property<int>("RuleType");

                    b.Property<int>("RuleVersion");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProductGroupId");

                    b.ToTable("LoyaltyGroupRule","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<bool>("IsArchived");

                    b.Property<long>("LoyaltyProgramId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<long>("ProductGroupId");

                    b.HasKey("Id");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("LoyaltyProgramId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("LoyaltyProductGroup","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("EndDate")
                        .IsRequired();

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("LoyaltyProgram","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<int>("Icon");

                    b.Property<bool>("IsArchived");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("ProductGroupId");

                    b.HasKey("Id");

                    b.HasIndex("ProductGroupId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("Product","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.ProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<int>("Icon");

                    b.Property<bool>("IsArchived");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("ProductGroup","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BurnDate");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<bool>("InternalPurchaseMadeBySystem");

                    b.Property<long>("LoyaltyProductGroupId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<long?>("ProductId");

                    b.Property<Guid>("UserId");

                    b.Property<decimal?>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProductGroupId");

                    b.ToTable("Purchase","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Venue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(200);

                    b.Property<int>("CategoryType");

                    b.Property<string>("City")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("FullDescription")
                        .HasMaxLength(4000);

                    b.Property<string>("Images");

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPublished");

                    b.Property<float?>("Latitude");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200);

                    b.Property<float?>("Longitude");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("OwnerId");

                    b.Property<long?>("ParentId");

                    b.Property<string>("Phones");

                    b.Property<int>("Type");

                    b.Property<string>("WebSites");

                    b.Property<string>("WorkingHours");

                    b.HasKey("Id");

                    b.ToTable("Venue","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Worker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Email");

                    b.Property<bool>("IsArchived");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("PhotoUri");

                    b.Property<string>("PositionName");

                    b.Property<int>("Role");

                    b.Property<long>("VenueId");

                    b.Property<Guid?>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.HasIndex("VenueId");

                    b.HasIndex("WorkerId", "VenueId")
                        .IsUnique()
                        .HasFilter("[WorkerId] IS NOT NULL");

                    b.ToTable("Worker","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyGroupRule", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.LoyaltyProductGroup")
                        .WithMany("Rules")
                        .HasForeignKey("LoyaltyProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProductGroup", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.LoyaltyProgram")
                        .WithMany("LoyaltyProductGroups")
                        .HasForeignKey("LoyaltyProgramId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Loyalty.Core.Entities.ProductGroup", "Group")
                        .WithMany("LoyaltyProductGroups")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProgram", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Venue", "OwnerVenue")
                        .WithMany("LoyaltyPrograms")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Product", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.ProductGroup", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Venue", "OwnerVenue")
                        .WithMany("ProductGroups")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Purchase", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.LoyaltyProductGroup")
                        .WithMany("Purchases")
                        .HasForeignKey("LoyaltyProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Worker", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Venue")
                        .WithMany("Workers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
