// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Loyalty.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20190214111219_AddedArchivedFields")]
    partial class AddedArchivedFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Loyalty.Data.Entities.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<bool>("IsArchived");

                    b.Property<long>("LoyaltyProductGroupId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProductGroupId");

                    b.ToTable("Card","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<bool>("IsArchived");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("Location","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<bool>("IsArchived");

                    b.Property<long>("LoyaltyProductGroupId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProductGroupId");

                    b.ToTable("LoyaltyProduct","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPublished");

                    b.Property<long>("LoyaltyProgramId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProgramId");

                    b.ToTable("LoyaltyProductGroup","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("LoyaltyProgram","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProgramRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<bool>("IsArchived");

                    b.Property<long?>("LoyaltyProgram");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<int>("RuleType");

                    b.Property<string>("RuleValue");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProgram")
                        .IsUnique()
                        .HasFilter("[LoyaltyProgram] IS NOT NULL");

                    b.ToTable("LoyaltyProgramRule","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BurnDate");

                    b.Property<long>("CardId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<decimal?>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Purchase","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.Venue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryType");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPublished");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("OwnerId");

                    b.Property<long?>("ParentId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Venue","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.VenueDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<bool>("IsArchived");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Phones")
                        .IsRequired();

                    b.Property<string>("PhotosUrl")
                        .IsRequired();

                    b.Property<long>("VenueId");

                    b.Property<string>("WebSites");

                    b.Property<string>("WorkingHours")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("VenueDetails","loyalty");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.Card", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.LoyaltyProductGroup")
                        .WithMany("Cards")
                        .HasForeignKey("LoyaltyProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Data.Entities.Location", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.Venue")
                        .WithOne("Location")
                        .HasForeignKey("Loyalty.Data.Entities.Location", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProduct", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.LoyaltyProductGroup")
                        .WithMany("LoyaltyProducts")
                        .HasForeignKey("LoyaltyProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProductGroup", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.LoyaltyProgram")
                        .WithMany("LoyaltyGroups")
                        .HasForeignKey("LoyaltyProgramId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProgram", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.Venue")
                        .WithMany("LoyaltyPrograms")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Data.Entities.LoyaltyProgramRule", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.LoyaltyProgram", "LoaLoyaltyProgramId")
                        .WithOne("LoyaltyRule")
                        .HasForeignKey("Loyalty.Data.Entities.LoyaltyProgramRule", "LoyaltyProgram");
                });

            modelBuilder.Entity("Loyalty.Data.Entities.Purchase", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.Card")
                        .WithMany("Purchases")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Data.Entities.VenueDetails", b =>
                {
                    b.HasOne("Loyalty.Data.Entities.Venue", "Venue")
                        .WithOne("VenueDetails")
                        .HasForeignKey("Loyalty.Data.Entities.VenueDetails", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
