// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Loyalty.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    internal class LoyaltyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Loyalty.Core.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<bool>("IsArchived");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("Location","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<bool>("IsArchived");

                    b.Property<long>("LoyaltyProgramId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<long?>("ProductGroupId");

                    b.Property<long?>("RuleId");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProgramId");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("RuleId");

                    b.ToTable("LoyaltyProductGroup","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("LoyaltyProgram","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProgramRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<bool>("IsArchived");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<int>("RuleType");

                    b.Property<string>("RuleValue");

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.ToTable("LoyaltyProgramRule","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Icon")
                        .IsRequired();

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long?>("ProductGroupId");

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("Product","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.ProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Icon")
                        .IsRequired();

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long>("VenueId");

                    b.HasKey("Id");

                    b.ToTable("ProductGroup","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BurnDate");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<long>("LoyaltyProductGroupId");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<Guid>("UserId");

                    b.Property<decimal?>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProductGroupId");

                    b.ToTable("Purchase","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Venue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryType");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsPublished");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("OwnerId");

                    b.Property<long?>("ParentId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Venue","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.VenueDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<bool>("IsArchived");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Phones")
                        .IsRequired();

                    b.Property<long>("VenueId");

                    b.Property<string>("WebSites");

                    b.Property<string>("WorkingHours")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("VenueDetails","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Worker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<string>("Email");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Modified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("PhotoUri");

                    b.Property<int>("Role");

                    b.Property<long>("VenueId");

                    b.Property<Guid>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Worker","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Location", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Venue")
                        .WithOne("Location")
                        .HasForeignKey("Loyalty.Core.Entities.Location", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProductGroup", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.LoyaltyProgram")
                        .WithMany("LoyaltyProductGroups")
                        .HasForeignKey("LoyaltyProgramId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Loyalty.Core.Entities.ProductGroup", "ProductGroup")
                        .WithMany()
                        .HasForeignKey("ProductGroupId");

                    b.HasOne("Loyalty.Core.Entities.LoyaltyProgramRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.LoyaltyProgram", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Venue")
                        .WithMany("LoyaltyPrograms")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Product", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Purchase", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.LoyaltyProductGroup")
                        .WithMany("Purchases")
                        .HasForeignKey("LoyaltyProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.VenueDetails", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Venue", "Venue")
                        .WithOne("VenueDetails")
                        .HasForeignKey("Loyalty.Core.Entities.VenueDetails", "VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Worker", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Venue")
                        .WithMany("Workers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
