// <auto-generated />
using System;
using Loyalty.Infrastructure.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Loyalty.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    partial class LoyaltyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.producteq", "'producteq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.productgroupeq", "'productgroupeq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.venueeq", "'venueeq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.workereq", "'workereq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyGroupRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<long>("LoyaltyProductGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProductGroupId");

                    b.ToTable("LoyaltyGroupRule","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<long>("LoyaltyProgramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ProductGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("LoyaltyProgramId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("LoyaltyProductGroup","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("LoyaltyProgram","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickUpTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlacedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VenueComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Order","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Orders.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.ProductGroups.ProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "productgroupeq")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Icon")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("ProductGroup","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "producteq")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalUid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Icon")
                        .HasColumnType("int");

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailableForOrder")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("ProductGroupId", "Name")
                        .IsUnique()
                        .HasFilter("[IsArchived] = 0");

                    b.ToTable("Product","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Purchases.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LoyaltyProductGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProductGroupId");

                    b.ToTable("Purchase","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Venues.Venue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "venueeq")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<bool>("AcceptsOrders")
                        .HasColumnType("bit");

                    b.Property<long>("CategoryType")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VenueStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Venue","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Workers.VenueWorker", b =>
                {
                    b.Property<long>("VenueId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("VenueId", "WorkerId");

                    b.HasIndex("VenueId", "WorkerId")
                        .IsUnique();

                    b.ToTable("VenueWorker","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Workers.Worker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "workereq")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhotoUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL)");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasFilter("([IsArchived] = 0 AND WorkerId IS NOT NULL)");

                    b.ToTable("Worker","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.UserCode", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("CodeValue")
                        .IsUnique();

                    b.ToTable("UserCode","loyalty");
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyGroupRule", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyProductGroup", "LoyaltyProductGroup")
                        .WithMany("Rules")
                        .HasForeignKey("LoyaltyProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyProductGroup", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyProgram", "LoyaltyProgram")
                        .WithMany("LoyaltyProductGroups")
                        .HasForeignKey("LoyaltyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loyalty.Core.Entities.Aggregates.ProductGroups.ProductGroup", "Group")
                        .WithMany("LoyaltyProductGroups")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyProgram", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.Venues.Venue", "OwnerVenue")
                        .WithMany("LoyaltyPrograms")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Orders.OrderItem", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Loyalty.Core.Entities.Aggregates.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.ProductGroups.ProductGroup", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.Venues.Venue", "OwnerVenue")
                        .WithMany("ProductGroups")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Products.Product", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.Venues.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Purchases.Purchase", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.LoyaltyPrograms.LoyaltyProductGroup", null)
                        .WithMany("Purchases")
                        .HasForeignKey("LoyaltyProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Venues.Venue", b =>
                {
                    b.OwnsOne("Loyalty.Core.Entities.Aggregates.Venues.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<long>("VenueId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Facebook")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Instagram")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phones")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Vkontakte")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WebSites")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VenueId");

                            b1.ToTable("Venue");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.OwnsOne("Loyalty.Core.Entities.Aggregates.Venues.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<long>("VenueId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(200)")
                                .HasMaxLength(200);

                            b1.Property<float?>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float?>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("VenueId");

                            b1.ToTable("Venue");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.OwnsOne("Loyalty.Core.Entities.Aggregates.Venues.ValueObjects.VenueDetails", "Details", b1 =>
                        {
                            b1.Property<long>("VenueId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(2000)")
                                .HasMaxLength(2000);

                            b1.Property<string>("FullDescription")
                                .HasColumnType("nvarchar(4000)")
                                .HasMaxLength(4000);

                            b1.Property<string>("WorkingHours")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VenueId");

                            b1.ToTable("Venue");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });
                });

            modelBuilder.Entity("Loyalty.Core.Entities.Aggregates.Workers.VenueWorker", b =>
                {
                    b.HasOne("Loyalty.Core.Entities.Aggregates.Workers.Worker", null)
                        .WithMany("VenueRoles")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
